### PR TITLE
Scaffolding baseline functionality

### PR DESCRIPTION
**Pull request by aendra-rininsland**
I've created an ES2015 class for the basic functionality of the project, as well as added a Mocha Chai test spec for that class. Also initialised package.json and .gitignore, added empty gulpfile. I'm happy to work on this side of it if somebody scaffolds out a build process for deploying as Chrome and/or Firefox browser extensions.

### CODE REVIEW

**Comment by aendra-rininsland** [comment]
Hold up, am needing to add Babel.

**Comment by phillipadsmith** [comment]
:+1:

**Comment by phillipadsmith** [comment]
@aendrew I'm getting this error on `npm test`, just FYI:

```
let chai = require('chai');
^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by aendra-rininsland** [comment]
@phillipadsmith Apologies for the lateness responding, seems like that's due to Babel not transpiling the unit tests as well. Will do a PR to fix that in a bit.

_Edit:_ Err, or everything's been changed to ES5. If you're not wanting to use ES2015, remove babel-core from `package.json` and update the spec, replacing `let` with `var` and `() =>` with `function()`

Good work BTW with getting everything rolling! Sorry I didn't get a chance to drop by Sunday!

**Pull request merged**
